[package]
name = "rgine"
version = "0.1.0"
edition = "2021"

[dependencies]
rgine_modules = { path = "core/modules/"}
rgine_platform = { path = "core/platform/", default-features = false}
rgine_graphics = { path = "core/graphics/", optional = true }

[features]
graphics = ["rgine_platform/window", "dep:rgine_graphics"]
default = ["graphics"]

[workspace]
members = [
  ".", 
  "core/*",
  "examples/*",
] 
