[package]
name = "rgine"
version = "0.1.0"
edition = "2021"

[dependencies]
rgine_modules = { path = "core/modules/"}
rgine_platform = { path = "core/platform/"}

[workspace]
members = [
  ".", 
  "core/*",
  "examples/*",
] 
